Feature/keycloak theme
uwcirg/ltt-environments pull request #4
Opened 2024-01-24 20:18 UTC by achen2401

https://www.pivotaltracker.com/story/show/186901516
screenshot of how it will look if works:
<img width="1159" alt="Screenshot 2024-01-24 at 12 16 29 PM" src="https://github.com/uwcirg/ltt-environments/assets/12942714/4f991950-30ef-4f8e-8bb2-73bf30e17deb">

2024-01-24 23:53 UTC, ivan-c requested changes
Thanks! Had a few suggestions but almost there

2024-01-24 23:53 UTC, ivan-c commented on dev/config/keycloak/themes/common/resources/lib/zocial/zocial-regular-webfont.eot
Can you move all the files in `dev/config/keycloak/themes` to `dev/config/keycloak/themes/ltt`? I wasn't able to configure the theme in keycloak until it was in its own (single) directory

2024-01-24 23:53 UTC, ivan-c commented on dev/config/keycloak/themes/common/resources/lib/zocial/zocial-regular-webfont.eot
Also, please add a line to the keycloak docker-compose config (see below diff) to mount the theme into the container

```
diff --git a/dev/docker-compose.yaml b/dev/docker-compose.yaml
index f11badb..cc264fd 100644
--- a/dev/docker-compose.yaml
+++ b/dev/docker-compose.yaml
@@ -149,6 +149,7 @@ services:
       - keycloak.env
     volumes:
       - ./config/keycloak/import/:/opt/keycloak/data/import:ro
+      - ./config/keycloak/themes/:/opt/keycloak/themes:ro
     depends_on:
       - db
     networks:
```

2024-01-25 00:02 UTC, ivan-c commented on dev/config/keycloak/themes/common/resources/lib/zocial/zocial-regular-webfont.eot
Whoops, this change too- to make `ltt` the default `loginTheme` for the `ltt` keycloak realm
```
diff --git a/dev/config/keycloak/import/ltt-realm.json b/dev/config/keycloak/import/ltt-realm.json
index 60c842f..bd9e5c1 100644
--- a/dev/config/keycloak/import/ltt-realm.json
+++ b/dev/config/keycloak/import/ltt-realm.json
@@ -752,6 +752,7 @@
     "user": "${KEYCLOAK_EMAIL_USER}",
     "password": "${KEYCLOAK_EMAIL_PASSWORD}"
   },
+  "loginTheme": "ltt",
   "eventsEnabled": false,
   "eventsListeners": [
     "jboss-logging"
```

2024-01-25 00:17 UTC, achen2401 commented
@ivan-c  thank you! I believe I addressed all your feedback.  Please let me know if you see any more issue.

2024-01-25 00:40 UTC, ivan-c approved these changes
Looks great, thank you! Please merge at your leisure

2024-01-25 00:47 UTC, merged